version: '3.4'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.1-management
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "passwordMy123"
      ACCEPT_EULA: "Y"
  authapi:
    image: authapi
    build:
      context: .
      dockerfile: ../makeupStore.Services.AuthAPI/Dockerfile
    ports:
      - 7002:7002
    depends_on:
      - db